In [1]:
import warnings

warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
# define path and set up dataframe
df_path = ('Linear_data.xlsx')
df1 = pd.read_excel(df_path,sheet_name='Train_Data')
df_path = ('Linear_data.xlsx')
df2 = pd.read_excel(df_path,sheet_name='Test_Data')

In [4]:
# convert categorical variables Divisions to dummy variables
df1 = pd.get_dummies(df1, columns=['DIVISION'],drop_first=True)
#df1 = pd.get_dummies(df1, columns=['TOPNB30'], drop_first=True, dummy_na=False)
# Convert all columns to float data type

In [5]:
# convert categorical variables Divisions to dummy variables
df2 = pd.get_dummies(df2, columns=['DIVISION'],drop_first=True)
# Convert all columns to float data type

In [6]:
df1 = df1.replace({True: 1, False: 0})
df1.head()

,OCC_YEAR,Population,B_E_CRIME,AREA_SQKM,Gross_Expenditure_Actual,Average of Average_income,Average of Unemployment_rate,DIVISION_D12,DIVISION_D13,DIVISION_D14,...,DIVISION_D31,DIVISION_D32,DIVISION_D33,DIVISION_D41,DIVISION_D42,DIVISION_D43,DIVISION_D51,DIVISION_D52,DIVISION_D53,DIVISION_D54_D55
0,2014,212644,255,18.678458,25008526,41609.166667,7.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2014,233111,226,24.780343,24858615,31510.000000,8.685714,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2014,196576,287,18.601911,21740037,56607.125000,6.925000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2014,284345,521,14.175254,31984099,38736.090909,7.172727,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2014,213428,521,68.121884,25545555,52676.538462,6.869231,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df2 = df2.replace({True: 1, False: 0})
df2.head()

,OCC_YEAR,Population,B_E_CRIME,AREA_SQKM,Gross_Expenditure_Actual,Average of Average_income,Average of Unemployment_rate,DIVISION_D12,DIVISION_D13,DIVISION_D14,...,DIVISION_D31,DIVISION_D32,DIVISION_D33,DIVISION_D41,DIVISION_D42,DIVISION_D43,DIVISION_D51,DIVISION_D52,DIVISION_D53,DIVISION_D54_D55
0,2020,212644,390,18.678458,25575001,41609.166667,7.000000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020,233111,203,24.780343,25839834,31510.000000,8.685714,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020,196576,366,18.601911,20044957,56607.125000,6.925000,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2020,284345,744,14.175254,35039845,38736.090909,7.172727,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2020,213428,399,68.121884,26946022,52676.538462,6.869231,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# data type Description
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OCC_YEAR                      96 non-null     int64
 1   Population                    96 non-null     int64
 2   B_E_CRIME                     96 non-null     int64
 3   AREA_SQKM                     96 non-null     float64
 4   Gross_Expenditure_Actual      96 non-null     int64
 5   Average of Average_income     96 non-null     float64
 6   Average of Unemployment_rate  96 non-null     float64
 7   DIVISION_D12                  96 non-null     int64
 8   DIVISION_D13                  96 non-null     int64
 9   DIVISION_D14                  96 non-null     int64
 10  DIVISION_D22                  96 non-null     int64
 11  DIVISION_D23                  96 non-null     int64
 12  DIVISION_D31                  96 non-null     int64
 13  DIVISION_D32                  96 non-null     int64
 14  DIVISION_D33                  96 non-null     int64
 15  DIVISION_D41                  96 non-null     int64
 16  DIVISION_D42                  96 non-null     int64
 17  DIVISION_D43                  96 non-null     int64
 18  DIVISION_D51                  96 non-null     int64
 19  DIVISION_D52                  96 non-null     int64
 20  DIVISION_D53                  96 non-null     int64
 21  DIVISION_D54_D55              96 non-null     int64
dtypes: float64(3), int64(19)
memory usage: 16.6 KB

In [9]:
# data type Description
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OCC_YEAR                      32 non-null     int64
 1   Population                    32 non-null     int64
 2   B_E_CRIME                     32 non-null     int64
 3   AREA_SQKM                     32 non-null     float64
 4   Gross_Expenditure_Actual      32 non-null     int64
 5   Average of Average_income     32 non-null     float64
 6   Average of Unemployment_rate  32 non-null     float64
 7   DIVISION_D12                  32 non-null     int64
 8   DIVISION_D13                  32 non-null     int64
 9   DIVISION_D14                  32 non-null     int64
 10  DIVISION_D22                  32 non-null     int64
 11  DIVISION_D23                  32 non-null     int64
 12  DIVISION_D31                  32 non-null     int64
 13  DIVISION_D32                  32 non-null     int64
 14  DIVISION_D33                  32 non-null     int64
 15  DIVISION_D41                  32 non-null     int64
 16  DIVISION_D42                  32 non-null     int64
 17  DIVISION_D43                  32 non-null     int64
 18  DIVISION_D51                  32 non-null     int64
 19  DIVISION_D52                  32 non-null     int64
 20  DIVISION_D53                  32 non-null     int64
 21  DIVISION_D54_D55              32 non-null     int64
dtypes: float64(3), int64(19)
memory usage: 5.6 KB

In [10]:
#  data Description
df1.describe()

,OCC_YEAR,Population,B_E_CRIME,AREA_SQKM,Gross_Expenditure_Actual,Average of Average_income,Average of Unemployment_rate,DIVISION_D12,DIVISION_D13,DIVISION_D14,...,DIVISION_D31,DIVISION_D32,DIVISION_D33,DIVISION_D41,DIVISION_D42,DIVISION_D43,DIVISION_D51,DIVISION_D52,DIVISION_D53,DIVISION_D54_D55
count,96.00000,96.000000,96.000000,96.000000,9.600000e+01,96.000000,96.000000,96.000000,96.000000,96.000000,...,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000
mean,2016.50000,238939.750000,453.010417,39.827027,2.836219e+07,42219.643091,8.399001,0.062500,0.062500,0.062500,...,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500
std,1.71679,55978.290557,155.395353,22.369369,6.074632e+06,17927.925379,1.312368,0.243332,0.243332,0.243332,...,0.243332,0.243332,0.243332,0.243332,0.243332,0.243332,0.243332,0.243332,0.243332,0.243332
min,2014.00000,148602.000000,210.000000,8.601683,1.996136e+07,25715.142857,6.869231,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.00000,208627.000000,309.500000,18.659321,2.509929e+07,31472.725000,7.106250,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2016.50000,237730.500000,452.500000,41.850740,2.743248e+07,37208.245455,8.390079,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2018.00000,283000.250000,537.250000,58.074211,3.074037e+07,43458.331667,9.552500,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2019.00000,346823.000000,910.000000,84.611749,4.897735e+07,103518.850000,11.157143,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
#  data Description
df2.describe()

,OCC_YEAR,Population,B_E_CRIME,AREA_SQKM,Gross_Expenditure_Actual,Average of Average_income,Average of Unemployment_rate,DIVISION_D12,DIVISION_D13,DIVISION_D14,...,DIVISION_D31,DIVISION_D32,DIVISION_D33,DIVISION_D41,DIVISION_D42,DIVISION_D43,DIVISION_D51,DIVISION_D52,DIVISION_D53,DIVISION_D54_D55
count,32.000000,32.000000,32.00000,32.000000,3.200000e+01,32.000000,32.000000,32.000000,32.000000,32.000000,...,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,2020.500000,238939.750000,394.50000,39.827027,2.873047e+07,42219.643091,8.399001,0.062500,0.062500,0.062500,...,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500,0.062500
std,0.508001,56577.005883,165.62628,22.608621,5.632638e+06,18119.673350,1.326404,0.245935,0.245935,0.245935,...,0.245935,0.245935,0.245935,0.245935,0.245935,0.245935,0.245935,0.245935,0.245935,0.245935
min,2020.000000,148602.000000,183.00000,8.601683,2.004496e+07,25715.142857,6.869231,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.000000,208627.000000,281.25000,18.659321,2.547497e+07,31472.725000,7.106250,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.500000,237730.500000,356.00000,41.850740,2.823776e+07,37208.245455,8.390079,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2021.000000,283000.250000,499.50000,58.074211,3.330551e+07,43458.331667,9.552500,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2021.000000,346823.000000,744.00000,84.611749,4.040919e+07,103518.850000,11.157143,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
# let's create a correlation matrix
#import seaborn as sns
#df1_corr = df1.corr(numeric_only=True)
#sns.heatmap(df1_corr,annot=True)

In [13]:
#Split the data into X test and y test
y_train = df1['B_E_CRIME']
X_train = df1.drop(columns=['B_E_CRIME','OCC_YEAR'])
#copying X into a variable called X_scaled for scaling to be used later
X_train_Scale = X_train.copy()
#scaling the data, even though we dont need for decision tree it will be useful when we do KNN
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit and transform the data
X_train_Scale = pd.DataFrame(scaler.fit_transform(X_train_Scale), columns=X_train_Scale.columns)

In [14]:
#Split the data into X train and y train
y_test = df2['B_E_CRIME']
X_test = df2.drop(columns=['B_E_CRIME','OCC_YEAR'])
#copying X into a variable called X_scaled for scaling to be used later
X_test_Scale = X_test.copy()
#scaling the data, even though we dont need for decision tree it will be useful when we do KNN
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit and transform the data
X_test_Scale = pd.DataFrame(scaler.fit_transform(X_test_Scale), columns=X_test_Scale.columns)

In [15]:
# Split the data into train and test sets
# y_test    X_test_Scale         y_train         X_train_Scale

In [16]:
# First, let's try forward stepwise regression
from stepwise_regression import step_reg

# Perform forward regression on the train set
forward_selected_predictors = step_reg.forward_regression(X_train_Scale, y_train, 0.05, verbose=True)

# Select the predictors from the train and test sets
X_train_Scale_forward = X_train_Scale[forward_selected_predictors]


# Fit the forward regression model
forward_model = sm.OLS(y_train, sm.add_constant(X_train_Scale_forward)).fit()

Add  Population                     with p-value 5.16769e-10
Add  DIVISION_D12                   with p-value 1.21969e-05
Add  Gross_Expenditure_Actual       with p-value 2.72941e-05
Add  DIVISION_D43                   with p-value 0.0017243
Add  DIVISION_D33                   with p-value 0.00451726
Add  DIVISION_D41                   with p-value 0.00764099
Add  Average of Average_income      with p-value 0.0189951
Add  DIVISION_D54_D55               with p-value 0.00269801
Add  DIVISION_D22                   with p-value 0.0248832

In [17]:
# Print the summary of the forward regression model
print(forward_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              B_E_CRIME   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.704
Method:                 Least Squares   F-statistic:                     26.10
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           4.75e-21
Time:                        21:17:19   Log-Likelihood:                -556.92
No. Observations:                  96   AIC:                             1134.
Df Residuals:                      86   BIC:                             1159.
Df Model:                           9
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                       453.0104      8.629     52.497      0.000     435.856     470.165
Population                  103.8178      9.671     10.735      0.000      84.593     123.043
DIVISION_D12                -37.5851      9.378     -4.008      0.000     -56.227     -18.943
Gross_Expenditure_Actual    112.9730     21.257      5.315      0.000      70.716     155.230
DIVISION_D43                -36.9391      9.307     -3.969      0.000     -55.440     -18.438
DIVISION_D33                 -3.4398     11.763     -0.292      0.771     -26.823      19.944
DIVISION_D41                 31.3800      8.931      3.514      0.001      13.627      49.133
Average of Average_income    43.1565     11.485      3.758      0.000      20.326      65.987
DIVISION_D54_D55            -61.4497     18.484     -3.324      0.001     -98.194     -24.705
DIVISION_D22                 20.3664      8.920      2.283      0.025       2.634      38.099
==============================================================================
Omnibus:                       14.891   Durbin-Watson:                   1.480
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.411
Skew:                           0.796   Prob(JB):                     0.000101
Kurtosis:                       4.437   Cond. No.                         4.76
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
# Second, let's try forward stepwise regression for test set
from stepwise_regression import step_reg

# Perform forward regression on the train set
forward_selected_predictors = step_reg.forward_regression(X_test_Scale, y_test, 0.05, verbose=True)

# Select the predictors from the train and test sets
X_test_Scale_forward = X_test_Scale[forward_selected_predictors]


# Fit the forward regression model
forward_model2 = sm.OLS(y_test, sm.add_constant(X_test_Scale_forward)).fit()

Add  Average of Unemployment_rate   with p-value 0.000862404
Add  Gross_Expenditure_Actual       with p-value 0.000200942
Add  DIVISION_D53                   with p-value 0.000421829
Add  DIVISION_D43                   with p-value 0.0234022

In [19]:
# Print the summary of the forward regression model for test set
print(forward_model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              B_E_CRIME   R-squared:                       0.778
Model:                            OLS   Adj. R-squared:                  0.745
Method:                 Least Squares   F-statistic:                     23.69
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           1.70e-08
Time:                        21:17:19   Log-Likelihood:                -184.31
No. Observations:                  32   AIC:                             378.6
Df Residuals:                      27   BIC:                             385.9
Df Model:                           4
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          394.5000     14.774     26.703      0.000     364.187     424.813
Average of Unemployment_rate   -61.6410     16.100     -3.829      0.001     -94.675     -28.607
Gross_Expenditure_Actual       112.5955     15.896      7.083      0.000      79.979     145.212
DIVISION_D53                    72.9601     16.227      4.496      0.000      39.665     106.255
DIVISION_D43                   -37.7341     15.703     -2.403      0.023     -69.954      -5.514
==============================================================================
Omnibus:                        1.646   Durbin-Watson:                   1.146
Prob(Omnibus):                  0.439   Jarque-Bera (JB):                1.118
Skew:                           0.153   Prob(JB):                        0.572
Kurtosis:                       2.137   Cond. No.                         1.75
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
# Predict on the train and test sets using the forward regression model
y_pred_forward_train = forward_model.predict(sm.add_constant(X_train_Scale_forward))
y_pred_forward_test = forward_model2.predict(sm.add_constant(X_test_Scale_forward))

# Calculate the MAE and RMSE for the forward regression model on the train and test sets
rmse_forward_train = mean_squared_error(y_train, y_pred_forward_train, squared=False)
rmse_forward_test = mean_squared_error(y_test, y_pred_forward_test, squared=False)
mae_forward_train = mean_absolute_error(y_train, y_pred_forward_train)
mae_forward_test = mean_absolute_error(y_test, y_pred_forward_test)

# Print the MAE and RMSE for the forward regression model on the train and test sets
print("RMSE (Forward Regression) - Train Set:", rmse_forward_train)
print("RMSE (Forward Regression) - Test Set:", rmse_forward_test)
print("MAE (Forward Regression) - Train Set:", mae_forward_train)
print("MAE (Forward Regression) - Test Set:", mae_forward_test)

RMSE (Forward Regression) - Train Set: 80.02493513144837
RMSE (Forward Regression) - Test Set: 76.76626397389556
MAE (Forward Regression) - Train Set: 59.568073352594276
MAE (Forward Regression) - Test Set: 63.856261749864366

In [21]:
# Perform backward regression on the train set
backward_selected_predictors = step_reg.backward_regression(X_train_Scale, y_train, 0.05, verbose=True)

# Select the predictors from the train and test sets
X_train_Scale_backward = X_train_Scale[backward_selected_predictors]
X_test_Scale_backward = X_test_Scale[backward_selected_predictors]

# Fit the backward regression model
backward_model = sm.OLS(y_train, sm.add_constant(X_train_Scale_backward)).fit()

Drop Average of Unemployment_rate   with p-value 0.923463
Drop DIVISION_D52                   with p-value 0.717323
Drop Population                     with p-value 0.79741
Drop DIVISION_D13                   with p-value 0.995208
Drop DIVISION_D22                   with p-value 0.967695
Drop DIVISION_D53                   with p-value 0.756094
Drop DIVISION_D43                   with p-value 0.226315
Drop DIVISION_D54_D55               with p-value 0.436834
Drop DIVISION_D12                   with p-value 0.0918656
Drop DIVISION_D31                   with p-value 0.130349
Drop DIVISION_D23                   with p-value 0.219664

In [22]:
# Print the summary of the backward regression model
print(backward_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              B_E_CRIME   R-squared:                       0.720
Model:                            OLS   Adj. R-squared:                  0.691
Method:                 Least Squares   F-statistic:                     24.56
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           2.99e-20
Time:                        21:17:19   Log-Likelihood:                -559.04
No. Observations:                  96   AIC:                             1138.
Df Residuals:                      86   BIC:                             1164.
Df Model:                           9
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                       453.0104      8.822     51.351      0.000     435.473     470.548
AREA_SQKM                    37.9851     13.369      2.841      0.006      11.408      64.562
Gross_Expenditure_Actual     87.5593     10.600      8.260      0.000      66.487     108.632
Average of Average_income    77.9179      9.992      7.798      0.000      58.055      97.781
DIVISION_D14                 53.2959      9.825      5.424      0.000      33.764      72.828
DIVISION_D32                 67.7606      9.678      7.002      0.000      48.522      86.999
DIVISION_D33                 38.4368     10.200      3.768      0.000      18.160      58.713
DIVISION_D41                 48.1262      9.198      5.232      0.000      29.841      66.411
DIVISION_D42                 43.4911     11.619      3.743      0.000      20.393      66.589
DIVISION_D51                 40.2487     10.098      3.986      0.000      20.174      60.323
==============================================================================
Omnibus:                       21.062   Durbin-Watson:                   1.634
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               29.569
Skew:                           1.021   Prob(JB):                     3.79e-07
Kurtosis:                       4.795   Cond. No.                         2.89
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
# Perform backward regression on the test set
backward_selected_predictors = step_reg.backward_regression(X_test_Scale, y_test, 0.05, verbose=True)

# Select the predictors from the train and test sets
X_test_Scale_backward = X_test_Scale[backward_selected_predictors]


# Fit the backward regression model
backward_model2 = sm.OLS(y_test, sm.add_constant(X_test_Scale_backward)).fit()

Drop Average of Average_income      with p-value 0.969018
Drop DIVISION_D53                   with p-value 0.922719
Drop AREA_SQKM                      with p-value 0.973465
Drop DIVISION_D23                   with p-value 0.993009
Drop DIVISION_D32                   with p-value 0.934045
Drop DIVISION_D41                   with p-value 0.251979
Drop DIVISION_D31                   with p-value 0.202669
Drop DIVISION_D43                   with p-value 0.191269
Drop DIVISION_D22                   with p-value 0.0630221
Drop Average of Unemployment_rate   with p-value 0.189065

In [24]:
# Print the summary of the backward regression model on test set
print(backward_model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              B_E_CRIME   R-squared:                       0.871
Model:                            OLS   Adj. R-squared:                  0.810
Method:                 Least Squares   F-statistic:                     14.21
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           3.20e-07
Time:                        21:17:19   Log-Likelihood:                -175.61
No. Observations:                  32   AIC:                             373.2
Df Residuals:                      21   BIC:                             389.4
Df Model:                          10
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                      394.5000     12.766     30.904      0.000     367.953     421.047
Population                  61.7190     17.473      3.532      0.002      25.382      98.056
Gross_Expenditure_Actual  -198.6983     34.910     -5.692      0.000    -271.297    -126.099
DIVISION_D12               -63.7587     13.685     -4.659      0.000     -92.219     -35.299
DIVISION_D13               -69.3862     17.386     -3.991      0.001    -105.543     -33.229
DIVISION_D14               114.5877     17.787      6.442      0.000      77.598     151.578
DIVISION_D33              -111.5079     18.820     -5.925      0.000    -150.647     -72.369
DIVISION_D42               -40.2418     14.496     -2.776      0.011     -70.387     -10.096
DIVISION_D51               145.4755     18.290      7.954      0.000     107.440     183.511
DIVISION_D52                86.7156     17.232      5.032      0.000      50.879     122.553
DIVISION_D54_D55           160.0241     22.843      7.005      0.000     112.519     207.529
==============================================================================
Omnibus:                        0.037   Durbin-Watson:                   1.549
Prob(Omnibus):                  0.982   Jarque-Bera (JB):                0.087
Skew:                          -0.048   Prob(JB):                        0.957
Kurtosis:                       2.763   Cond. No.                         5.32
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
# Predict on the train and test sets using the backward regression model
y_pred_backward_train = backward_model.predict(sm.add_constant(X_train_Scale_backward))
y_pred_backward_test = backward_model2.predict(sm.add_constant(X_test_Scale_backward))

# Calculate the MAE and RMSE for the backward regression model on the train and test sets
mae_backward_train = mean_absolute_error(y_train, y_pred_backward_train)
mae_backward_test = mean_absolute_error(y_test, y_pred_backward_test)
rmse_backward_train = mean_squared_error(y_train, y_pred_backward_train, squared=False)
rmse_backward_test = mean_squared_error(y_test, y_pred_backward_test, squared=False)

# Print the MAE and RMSE for the backward regression model on the train and test sets
print("MAE (Backward Regression) - Train Set:", mae_backward_train)
print("MAE (Backward Regression) - Test Set:", mae_backward_test)
print("RMSE (Backward Regression) - Train Set:", rmse_backward_train)
print("RMSE (Backward Regression) - Test Set:", rmse_backward_test)

MAE (Backward Regression) - Train Set: 62.42426176513302
MAE (Backward Regression) - Test Set: 47.72117383915153
RMSE (Backward Regression) - Train Set: 81.80989488907483
RMSE (Backward Regression) - Test Set: 58.49895665104976

In [26]:
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV
import numpy as np

# Ridge Regression
ridge_model1 = RidgeCV(alphas=np.logspace(-6, 6, 20), cv=5) 
ridge_model1.fit(X_train_Scale, y_train)

# Print Ridge Regression summary
print("Ridge Regression:")
print("Best alpha:", ridge_model1.alpha_)
print("Coefficients:", ridge_model1.coef_)
print("Intercept:", ridge_model1.intercept_)
print("")

Ridge Regression:
Best alpha: 2.06913808111479
Coefficients: [ 44.34150946  27.33746488  58.74144229  23.57823635   4.7743301
 -28.55014162  -1.85311217  35.39666302  17.15975216 -11.97412347
 -14.33633275  38.03745027   3.94655358  34.71827624  13.45361033
 -15.2576469   33.84100167  13.02238613  22.46831951   3.45462406]
Intercept: 453.0104166666667

In [27]:
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV
import numpy as np

# Ridge Regression
ridge_model2 = RidgeCV(alphas=np.logspace(-6, 6, 20), cv=5) 
ridge_model2.fit(X_test_Scale, y_test)

# Print Ridge Regression summary
print("Ridge Regression:")
print("Best alpha:", ridge_model2.alpha_)
print("Coefficients:", ridge_model2.coef_)
print("Intercept:", ridge_model2.intercept_)
print("")

Ridge Regression:
Best alpha: 0.00615848211066026
Coefficients: [  77.5723651    -7.85107383 -364.59550131    3.90520737   58.68512039
  -63.84982495  -86.08207527  201.18664694   41.00049216   -3.05029833
   27.93562789   23.39501857 -154.37135546   19.89327928  -38.87236428
   45.42715997  238.88743603  147.51441907    5.43247441  277.11071558]
Intercept: 394.5

In [28]:
# LASSO Regression
lasso_model1 = LassoCV(alphas=np.logspace(-6, 6, 20), cv=5)
lasso_model1.fit(X_train_Scale, y_train)

# Print LASSO Regression summary
print("LASSO Regression:")
print("Best alpha:", lasso_model1.alpha_)
print("Coefficients:", lasso_model1.coef_)
print("Intercept:", lasso_model1.intercept_)
print("")

LASSO Regression:
Best alpha: 0.4832930238571752
Coefficients: [ 72.26608458  21.07754861  65.06697139  32.53535852   0.
 -27.21302509  -0.          26.12238151  19.74074005  -0.
  -0.          26.33034521   0.          39.95787121  11.06385126
 -17.81423211  28.45325316  21.94306208  14.0116518   -6.42178438]
Intercept: 453.0104166666667

In [29]:
# LASSO Regression
lasso_model2 = LassoCV(alphas=np.logspace(-6, 6, 20), cv=5)
lasso_model2.fit(X_test_Scale, y_test)

# Print LASSO Regression summary
print("LASSO Regression:")
print("Best alpha:", lasso_model2.alpha_)
print("Coefficients:", lasso_model2.coef_)
print("Intercept:", lasso_model2.intercept_)
print("")

LASSO Regression:
Best alpha: 1e-06
Coefficients: [ 107.34364355   38.15562192 -393.06790823  -48.86060219   46.27283281
  -73.01992822  -79.76638179  205.32337912   26.41676839  -14.65893076
   26.74799329   -8.2138614  -188.89427336    9.03105624  -85.5153994
   25.74509741  256.4837037   170.31408034   35.8386495   278.57937178]
Intercept: 394.5

In [30]:
# ElasticNet Regression
elasticnet_model1 = ElasticNetCV(alphas=np.logspace(-6, 6, 20), l1_ratio=np.linspace(0.1, 1.0, 10), cv=5)
elasticnet_model1.fit(X_train_Scale, y_train)

# Print ElasticNet Regression summary
print("ElasticNet Regression:")
print("Best alpha:", elasticnet_model1.alpha_)
print("Best L1 ratio:", elasticnet_model1.l1_ratio_)
print("Coefficients:", elasticnet_model1.coef_)
print("Intercept:", elasticnet_model1.intercept_)
print("")

ElasticNet Regression:
Best alpha: 0.11288378916846883
Best L1 ratio: 0.8
Coefficients: [ 46.10276498  27.87240827  58.25089163  22.51813329   2.09851025
 -28.46407023  -2.06053972  34.43947979  16.34833089 -10.99213861
 -12.57648959  36.72382571   3.29571926  35.111581    12.84728873
 -15.10372726  33.29094687  13.86238915  22.34819831   2.99540893]
Intercept: 453.0104166666667

In [31]:
# ElasticNet Regression
elasticnet_model2 = ElasticNetCV(alphas=np.logspace(-6, 6, 20), l1_ratio=np.linspace(0.1, 1.0, 10), cv=5)
elasticnet_model2.fit(X_test_Scale, y_test)

# Print ElasticNet Regression summary
print("ElasticNet Regression:")
print("Best alpha:", elasticnet_model2.alpha_)
print("Best L1 ratio:", elasticnet_model2.l1_ratio_)
print("Coefficients:", elasticnet_model2.coef_)
print("Intercept:", elasticnet_model2.intercept_)
print("")

ElasticNet Regression:
Best alpha: 0.0003359818286283781
Best L1 ratio: 0.5
Coefficients: [  94.09332925   26.5875822  -363.0102897   -33.59626793   46.41106178
  -68.91006089  -77.09164942  195.94344477   27.60903905  -13.61860449
   24.28180825    0.3944331  -171.57745795   10.52186217  -71.07502935
   26.65445737  241.87708953  156.15099657   30.2640558   265.24885663]
Intercept: 394.5

In [32]:
# Predict on train and test sets
y_pred_ridge_train = ridge_model1.predict(X_train_Scale)
y_pred_ridge_test = ridge_model2.predict(X_test_Scale)

y_pred_lasso_train = lasso_model1.predict(X_train_Scale)
y_pred_lasso_test = lasso_model2.predict(X_test_Scale)

y_pred_elasticnet_train = elasticnet_model1.predict(X_train_Scale)
y_pred_elasticnet_test = elasticnet_model2.predict(X_test_Scale)

In [33]:
# Calculate metrics for each model
ridge_rmse_train = mean_squared_error(y_train, y_pred_ridge_train, squared=False)
ridge_rmse_test = mean_squared_error(y_test, y_pred_ridge_test, squared=False)
ridge_mae_train = mean_absolute_error(y_train, y_pred_ridge_train)
ridge_mae_test = mean_absolute_error(y_test, y_pred_ridge_test)
ridge_r2_train = r2_score(y_train, y_pred_ridge_train)
ridge_r2_test = r2_score(y_test, y_pred_ridge_test)

lasso_rmse_train = mean_squared_error(y_train, y_pred_lasso_train, squared=False)
lasso_rmse_test = mean_squared_error(y_test, y_pred_lasso_test, squared=False)
lasso_mae_train = mean_absolute_error(y_train, y_pred_lasso_train)
lasso_mae_test = mean_absolute_error(y_test, y_pred_lasso_test)
lasso_r2_train = r2_score(y_train, y_pred_lasso_train)
lasso_r2_test = r2_score(y_test, y_pred_lasso_test)

elasticnet_rmse_train = mean_squared_error(y_train, y_pred_elasticnet_train, squared=False)
elasticnet_rmse_test = mean_squared_error(y_test, y_pred_elasticnet_test, squared=False)
elasticnet_mae_train = mean_absolute_error(y_train, y_pred_elasticnet_train)
elasticnet_mae_test = mean_absolute_error(y_test, y_pred_elasticnet_test)
elasticnet_r2_train = r2_score(y_train, y_pred_elasticnet_train)
elasticnet_r2_test = r2_score(y_test, y_pred_elasticnet_test)

print ("ridge_rmse_train:", mean_squared_error(y_train, y_pred_ridge_train, squared=False))
print ("ridge_rmse_test:",mean_squared_error(y_test, y_pred_ridge_test, squared=False))
print ("ridge_mae_train:", mean_absolute_error(y_train, y_pred_ridge_train))
print ("ridge_mae_test:", mean_absolute_error(y_test, y_pred_ridge_test))
print ("ridge_r2_train:", r2_score(y_train, y_pred_ridge_train))
print ("ridge_r2_test:", r2_score(y_test, y_pred_ridge_test))


print ("lasso_rmse_train:", mean_squared_error(y_train, y_pred_lasso_train, squared=False))
print ("lasso_rmse_test:", mean_squared_error(y_test, y_pred_lasso_test, squared=False))
print ("lasso_mae_train:", mean_absolute_error(y_train, y_pred_lasso_train))
print ("lasso_mae_test:", mean_absolute_error(y_test, y_pred_lasso_test))
print ("lasso_r2_train:", r2_score(y_train, y_pred_lasso_train))
print ("lasso_r2_test:", r2_score(y_test, y_pred_lasso_test))


print ("elasticnet_rmse_train:", mean_squared_error(y_train, y_pred_elasticnet_train, squared=False))
print ("elasticnet_rmse_test:", mean_squared_error(y_test, y_pred_elasticnet_test, squared=False))
print ("elasticnet_mae_train:", mean_absolute_error(y_train, y_pred_elasticnet_train))
print ("elasticnet_mae_test:", mean_absolute_error(y_test, y_pred_elasticnet_test))
print ("elasticnet_r2_train:", r2_score(y_train, y_pred_elasticnet_train))
print ("elasticnet_r2_test:", r2_score(y_test, y_pred_elasticnet_test))

ridge_rmse_train: 77.87173705633174
ridge_rmse_test: 44.37521976229229
ridge_mae_train: 56.57732768991519
ridge_mae_test: 37.325906966927796
ridge_r2_train: 0.7462352476482474
ridge_r2_test: 0.9259012597378914
lasso_rmse_train: 77.77860139443665
lasso_rmse_test: 44.30662974962422
lasso_mae_train: 56.50579477714563
lasso_mae_test: 37.3562388859191
lasso_r2_train: 0.7468418968754891
lasso_r2_test: 0.9261301489984064
elasticnet_rmse_train: 77.90839260523306
elasticnet_rmse_test: 44.38138143059008
elasticnet_mae_train: 56.64570954478834
elasticnet_mae_test: 37.32421822629797
elasticnet_r2_train: 0.7459962886646962
elasticnet_r2_test: 0.9258806805245559